name: Terraform

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

env:
  TERRAFORM_VERSION: 1.4.6
  DEFAULT_BRANCH_CONFIG: |
    {
    "TERRAFORM_DIR": ".",
    "BRANCHES": [
        {
            "BRANCH": "default",
            "WORKSPACE": "default",
            "VARFILES": [
                "terraform.tfvars"
            ],
            "SHOULD_PLAN": true,
            "SHOULD_APPLY": true
        }
      ]
    }

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      varfile: ${{ steps.branch-check.outputs.varfile }}
      workspace: ${{ steps.branch-check.outputs.workspace }}
      terraform_dir: ${{ steps.branch-check.outputs.terraform_dir }}
      should_plan: ${{ steps.branch-check.outputs.should_plan }}
      should_apply: ${{ steps.branch-check.outputs.should_apply }}
    steps:
      - name: Parse Configuration
        id: parse-config
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"

          if [ -f "tf-cfg.yaml" ]; then
              BRANCH_CONFIG=$(cat tf-cfg.yaml | yq eval '.BRANCHES[] | select(.BRANCH == env(BRANCH_NAME))')
          elif [ -f "tf-cfg.json" ]; then
              BRANCH_CONFIG=$(cat tf-cfg.json | yq eval '.BRANCHES[] | select(.BRANCH == env(BRANCH_NAME))')
          else
              BRANCH_CONFIG="${{ env.DEFAULT_BRANCH_CONFIG }}"
          fi

          WORKSPACE=$(echo "$BRANCH_CONFIG" | yq eval ".WORKSPACE" -)
          VARFILE=$(echo "$BRANCH_CONFIG" | yq eval ".VARFILE" -)
          SHOULD_PLAN=$(echo "BRANCH_$CONFIG" | yq eval ".SHOULD_PLAN" -)
          SHOULD_APPLY=$(echo "BRANCH_$CONFIG" | yq eval ".SHOULD_APPLY" -)

          echo "workspace=$WORKSPACE" >> $GITHUB_OUTPUT
          echo "varfile=$VARFILE" >> $GITHUB_OUTPUT
          echo "should_plan=$SHOULD_PLAN" >> $GITHUB_OUTPUT
          echo "should_apply=$SHOULD_APPLY" >> $GITHUB_OUTPUT
